// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package agent

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sensorOpenScratch struct {
	_        structs.HostLayout
	PathHint [256]int8
	Flags    int32
}

// loadSensor returns the embedded CollectionSpec for sensor.
func loadSensor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SensorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sensor: %w", err)
	}

	return spec, err
}

// loadSensorObjects loads sensor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sensorObjects
//	*sensorPrograms
//	*sensorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSensorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSensor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sensorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorSpecs struct {
	sensorProgramSpecs
	sensorMapSpecs
	sensorVariableSpecs
}

// sensorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorProgramSpecs struct {
	TpSchedProcessExec *ebpf.ProgramSpec `ebpf:"tp_sched_process_exec"`
	TpSchedProcessExit *ebpf.ProgramSpec `ebpf:"tp_sched_process_exit"`
	TpSchedProcessFork *ebpf.ProgramSpec `ebpf:"tp_sched_process_fork"`
	TpSysEnterFchmodat *ebpf.ProgramSpec `ebpf:"tp_sys_enter_fchmodat"`
	TpSysEnterOpenat   *ebpf.ProgramSpec `ebpf:"tp_sys_enter_openat"`
	TpSysExitOpenat    *ebpf.ProgramSpec `ebpf:"tp_sys_exit_openat"`
}

// sensorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorMapSpecs struct {
	ChmodEvents    *ebpf.MapSpec `ebpf:"chmod_events"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	OpenEvents     *ebpf.MapSpec `ebpf:"open_events"`
	OpenScratchMap *ebpf.MapSpec `ebpf:"open_scratch_map"`
	PidToRoot      *ebpf.MapSpec `ebpf:"pid_to_root"`
}

// sensorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorVariableSpecs struct {
}

// sensorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorObjects struct {
	sensorPrograms
	sensorMaps
	sensorVariables
}

func (o *sensorObjects) Close() error {
	return _SensorClose(
		&o.sensorPrograms,
		&o.sensorMaps,
	)
}

// sensorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorMaps struct {
	ChmodEvents    *ebpf.Map `ebpf:"chmod_events"`
	Events         *ebpf.Map `ebpf:"events"`
	OpenEvents     *ebpf.Map `ebpf:"open_events"`
	OpenScratchMap *ebpf.Map `ebpf:"open_scratch_map"`
	PidToRoot      *ebpf.Map `ebpf:"pid_to_root"`
}

func (m *sensorMaps) Close() error {
	return _SensorClose(
		m.ChmodEvents,
		m.Events,
		m.OpenEvents,
		m.OpenScratchMap,
		m.PidToRoot,
	)
}

// sensorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorVariables struct {
}

// sensorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorPrograms struct {
	TpSchedProcessExec *ebpf.Program `ebpf:"tp_sched_process_exec"`
	TpSchedProcessExit *ebpf.Program `ebpf:"tp_sched_process_exit"`
	TpSchedProcessFork *ebpf.Program `ebpf:"tp_sched_process_fork"`
	TpSysEnterFchmodat *ebpf.Program `ebpf:"tp_sys_enter_fchmodat"`
	TpSysEnterOpenat   *ebpf.Program `ebpf:"tp_sys_enter_openat"`
	TpSysExitOpenat    *ebpf.Program `ebpf:"tp_sys_exit_openat"`
}

func (p *sensorPrograms) Close() error {
	return _SensorClose(
		p.TpSchedProcessExec,
		p.TpSchedProcessExit,
		p.TpSchedProcessFork,
		p.TpSysEnterFchmodat,
		p.TpSysEnterOpenat,
		p.TpSysExitOpenat,
	)
}

func _SensorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sensor_x86_bpfel.o
var _SensorBytes []byte
